### ISSUE TITLE
panic: repeated read on failed websocket connection

### ISSUE THREAD

**Issue by rebootcode** [fasthttp/websocket#19]
I am having panic fatal error, whenever client tries to reconnect

```go
panic: repeated read on failed websocket connection

goroutine 67 [running]:
github.com/fasthttp/websocket.(*Conn).NextReader(0xc005a14160, 0xffffffffffffffff, 0x0, 0x0, 0xc5f5a0, 0xc00000f500)
        /home/ubuntu/go/pkg/mod/github.com/fasthttp/websocket@v1.4.2/conn.go:1001 +0x343
github.com/fasthttp/websocket.(*Conn).ReadMessage(0xc005a14160, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0xc5f5a0, 0xc00000f500)
        /home/ubuntu/go/pkg/mod/github.com/fasthttp/websocket@v1.4.2/conn.go:1064 +0x2f
main.main.func10(0xc0003d38e0)
        /home/ubuntu/go/src/projectTwo/main.go:309 +0x1ea
github.com/gofiber/websocket.New.func2.2(0xc005a14160)
        /home/ubuntu/go/pkg/mod/github.com/gofiber/websocket@v0.3.0/main.go:91 +0xab
github.com/fasthttp/websocket.(*FastHTTPUpgrader).Upgrade.func1(0xc6ffe0, 0xc0003d0cc0)
        /home/ubuntu/go/pkg/mod/github.com/fasthttp/websocket@v1.4.2/server_fasthttp.go:201 +0x227
github.com/valyala/fasthttp.hijackConnHandler(0xc5f140, 0xc0001f6ae0, 0xc70160, 0xc00031ef90, 0xc000148c00, 0xc00023cf40)
        /home/ubuntu/go/pkg/mod/github.com/valyala/fasthttp@v1.12.0/server.go:2228 +0x7b
created by github.com/valyala/fasthttp.(*Server).serveConn
        /home/ubuntu/go/pkg/mod/github.com/valyala/fasthttp@v1.12.0/server.go:2189 +0xa82
exit status 2
```
My main.go:309 line is: 
```go
_, data, err := c.ReadMessage()
```

**Comment by rebootcode** [comment]
Is this bug of gorilla/websocket - https://github.com/gorilla/websocket/issues/476
